.PHONY: php
php:
	@clear
	@nix develop ~/projects/nixities#temporary.wasmio.wlr --command go run . --run-php

.PHONY: shell
shell:
	nix develop ~/projects/nixities#temporary.wasmio.wlr

.PHONY: clean
clean:
